on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Replace with your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt # Assuming you have a requirements.txt file

      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
          NOTION_TASKS_DB_ID: ${{ secrets.NOTION_TASKS_DB_ID }}
          NOTION_PROJECTS_DB_ID: ${{ secrets.NOTION_PROJECTS_DB_ID }}
          NOTION_VARIABLES_DB_ID: ${{ secrets.NOTION_VARIABLES_DB_ID }}
        run: python main.py
